[package]
name = "midisploder"
version = "0.1.0"
authors = ["Tomek Rabczak <tomek.rabczak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4"
